// Generated from the design handoff (Widgeon Brand System.dc.html) + composited
// crown/hat royalty variants — do not hand-edit; regenerate via the sprite pipeline.
// 16-wide pixel sprites + color map, rendered by PixelSpriteView.

enum PixelSprites {
    /// Character -> hex color. Any sprite char absent here (e.g. ".") is transparent.
    static let palette: [Character: String] = [
        "A": "#8FAE4C",
        "B": "#141019",
        "C": "#EDE3C8",
        "D": "#5F7E33",
        "G": "#7C8194",
        "K": "#141019",
        "M": "#C95AD8",
        "N": "#B5794A",
        "O": "#FF8A2B",
        "R": "#E4506A",
        "T": "#5EBE86",
        "W": "#FFFFFF",
        "Y": "#FFD24C",
        "b": "#9BD1F5",
        "c": "#FFF6E9",
        "d": "#FBE39A",
        "e": "#F2CE6E",
        "f": "#FF9E7D",
        "g": "#A6ABBE",
        "h": "#E9CF9F",
        "k": "#4A3B5C",
        "l": "#C3B5FF",
        "m": "#9BE3C9",
        "n": "#7A4E2B",
        "o": "#FFC36E",
        "p": "#FF9BB0",
        "r": "#FF9EC4",
        "s": "#C8B57E",
        "t": "#8FD98A",
        "w": "#FFFFFF",
        "x": "#FFF3D4",
        "y": "#E7A70E",
    ]

    /// Sprite key -> rows of a pixel grid.
    static let grids: [String: [String]] = [
        "bit": ["................", "................", "................", "................", "......M..M......", ".....MMMMMM.....", "....MM.MM.MM....", "....MMMMMMMM....", ".....M....M.....", "................", "................", "................", "................", "................", "................", "................"],
        "blob": ["................", "................", "...M.......M....", "....M.....M.....", "...MMMMMMMMM....", "..MM.MMMMM.MM...", ".MMMMMMMMMMMMM..", ".M.MMMMMMMMM.M..", ".M.M.......M.M..", "....MM...MM.....", "................", "................", "................", "................", "................", "................"],
        "cat": ["................", "..K.......K.....", "..KK.....KK.....", "..KgK...KgK.....", "..KggggggggK....", ".KggggggggggK...", ".KgWBggggBWgK...", ".KgggppgggggK...", ".KggggggggggK...", ".KggggggggggK...", "..KgggggggggK...", "..KggggggggK....", "...KgggggggK....", "....KgggggK.....", ".....KKKKK......", "................"],
        "cat2": ["................", "..K......K......", "..KgK....KgK....", "..KggK..KggK....", ".KggggKKggggK...", ".KggggggggggK...", ".KgWBggggWBgK...", ".KggggggggggK...", ".KgggKppKgggK...", ".KggggggggggK...", "..KggggggggK.K..", "..KggggggggKKgK.", "..KggggggggKgK..", ".KGggggggggGK...", "...K..KK..K.....", "................"],
        "catA": ["....................", "...K.......K........", "...KK.....KK........", "...KgpK..KpgK.......", "..KgggKKKgggK.......", "..KgGgggggGgK.......", "..KgWKggggKWgK......", "..KggggppggggK......", "..KgggggggggK.......", "...KgggggggK........", "..KgggGgGgggK.......", ".KggggGgGggggK......", ".KgggggggggggK.KKK..", ".KgggggggggggKKggK..", ".KgggggggggggKggK...", ".KGgggggggggGKK.....", "..KK..KKK..KK......."],
        "catB": ["....................", ".....K.....K........", ".....KK...KK........", ".....KgK.KgK........", "....KgpgKgpgK.......", "....KgggggggK.......", "...KgggggggggK......", "...KgWKgggKWgK......", "...KgggggggggK......", "...KggKpppKggK......", "....KgggggggK.......", "....KgggggggK.......", ".....KgggggK.KK.....", "......KgggK.KgK.....", ".......KKK..KK......"],
        "catCrown": [".....Y.Y.Y......", ".....YYYYY......", "..K.......K.....", "..KK.....KK.....", "..KgK...KgK.....", "..KggggggggK....", ".KggggggggggK...", ".KgWBggggBWgK...", ".KgggppgggggK...", ".KggggggggggK...", ".KggggggggggK...", "..KgggggggggK...", "..KggggggggK....", "...KgggggggK....", "....KgggggK.....", ".....KKKKK......", "................"],
        "catHat": [".....KKKKK......", ".....KKKKK......", ".....KYYYK......", "....KKKKKKK.....", "..K.......K.....", "..KK.....KK.....", "..KgK...KgK.....", "..KggggggggK....", ".KggggggggggK...", ".KgWBggggBWgK...", ".KgggppgggggK...", ".KggggggggggK...", ".KggggggggggK...", "..KgggggggggK...", "..KggggggggK....", "...KgggggggK....", "....KgggggK.....", ".....KKKKK......", "................"],
        "catT": ["....................", "....K.....K.........", "....KK...KK.........", "....KgpK.KpgK.......", "...KgggKKgggK.......", "...KgggggggggK......", "...KgWKgggKWgK......", "...KggggpggggK......", "....KgggggggK.......", "....KgggggggK.......", "...KgggggggggK......", "...KgggggggggK.KK...", "..KggggggggggKKgK...", "..KggggggggggKgK....", "..KGggggggggGKK.....", "...KK.KKK.KK........"],
        "dog": ["................", "...KKKK.........", "..KNNNNK........", ".KnKNNNNK.......", ".KnKWBNNKK......", ".KnKNNNNKnK.....", "..KNNNNNNKK.....", "..KNNNNNNK......", ".KNNNNNNNNK.....", "KNNNNNNNNNNK..K.", "KNNNnnnNNNNK.KK.", "KNNNnnnNNNNKKK..", ".KNNNNNNNNK.....", "..KNNNNNNK......", "...K..K.K.......", "................"],
        "dogA": ["....................", "...KKKKKK...........", "..KNNNNNNK..........", ".KnnKNNNNNK.........", ".KnnKNWKnnNK........", ".KnnKNNNnnNK........", ".KnnKNNNNNNK........", "..KKNhhhhhNK........", "...KNhhKKhhK........", "...KNhhhhhK.........", "....KRRKKK..........", "...KNNNNNNK.........", "..KNNNNNNNNKK.......", ".KNNnnNNNNNNNK..K...", ".KNNnnNNNNNNNK.KnK..", ".KNNNNNNNNNNNKKnnK..", "..KNNNNNNNNNKKnK....", "...KNNNNNNNNKK......", "....KK..KK.KK......."],
        "dogB": ["....................", ".....KKKKK..........", "....KNNNNNK.........", "...KnKNNNNNKK.......", "...KnKNWKNNKnK......", "...KnKNNNNNKnK......", "....KNNhhhNKK.......", "....KNhhKhhK........", ".....KNhhhK.........", "....KNNNNNNK........", "...KNNNNNNNNK.......", "...KNNNNNNNNK.K.....", "....KNNNNNNKKnK.....", ".....KKKKKK.KK......"],
        "dogCrown": [".....Y.Y.Y......", ".....YYYYY......", "...KKKK.........", "..KNNNNK........", ".KnKNNNNK.......", ".KnKWBNNKK......", ".KnKNNNNKnK.....", "..KNNNNNNKK.....", "..KNNNNNNK......", ".KNNNNNNNNK.....", "KNNNNNNNNNNK..K.", "KNNNnnnNNNNK.KK.", "KNNNnnnNNNNKKK..", ".KNNNNNNNNK.....", "..KNNNNNNK......", "...K..K.K.......", "................"],
        "dogHat": [".....KKKKK......", ".....KKKKK......", ".....KYYYK......", "....KKKKKKK.....", "...KKKK.........", "..KNNNNK........", ".KnKNNNNK.......", ".KnKWBNNKK......", ".KnKNNNNKnK.....", "..KNNNNNNKK.....", "..KNNNNNNK......", ".KNNNNNNNNK.....", "KNNNNNNNNNNK..K.", "KNNNnnnNNNNK.KK.", "KNNNnnnNNNNKKK..", ".KNNNNNNNNK.....", "..KNNNNNNK......", "...K..K.K.......", "................"],
        "dogT": ["....................", "....KKKKK...........", "...KNNNNNK..........", "..KnnKNNNNK.........", "..KnnKNWKNNK........", "..KnnKNNNNNK........", "...KKNhhhhNK........", "....KNhhKhhK........", "....KNhhhhK.........", "....KNNNNNK.........", "...KNNNNNNNK........", "..KNNnnNNNNNK.......", "..KNNnnNNNNNK..KK...", "..KNNNNNNNNNK.KnK...", "...KNNNNNNNKKKnK....", "...KNNNNNNNKnKK.....", "....KK.KK.KKK......."],
        "duck": ["................", "....KKKK........", "...KYYYYK.......", "..KYWBYYK.......", "..KYYYYYKOOO....", "..KYYYYYKOOO....", "..KYYYYYK.......", ".KYYYYYYYYK.....", "KYYYyyyYYYYK....", "KYYYyyyYYYYK....", "KYYYyyyYYYYK....", "KYYYYYYYYYYK....", ".KYYYYYYYYK.....", "..KYYYYYYK......", "...O..O.O.......", "................"],
        "duckA": ["....................", ".....KKKKK..........", "....KYYYYYK.........", "...KYWKYYYYK........", "...KYYYYYYYKOOOO....", "...KYYYYYYYKOOOO....", "....KYYYYYK.........", "....KYYYYYK.........", "...KYYYYYYYKK.......", "..KYYYYYYYYYYKK.....", ".KYYYxxxxxxYYYYK....", "KYYYYxyyyyxYYYYYK...", "KYYYxyyyyyyxYYYYK...", "KYYYxyyyyyyxYYYYYK..", ".KYYYxyyyyxYYYYYK...", "..KYYYxxxxYYYYYK....", "...KYYYYYYYYYYK.....", "....KKKKKKKKKK......", ".....O...O..O......."],
        "duckB": ["....................", ".......KKKK.........", "......KYYYYK........", ".....KYWKYYYK.......", ".....KYYYYYYKOO.....", ".....KYYYYYYKOO.....", "....KYYYYYYYK.......", "....KYYYYYYYYK......", "...KYYYYxxYYYYK.....", "...KYYYxxxxYYYK.....", "...KYYYxxxxYYYK.....", "....KYYYxxYYYK......", ".....KYYYYYYK.......", "......KKKKKK........", ".......O..O........."],
        "duckP": ["................", "....kkkk........", "...kddddk.......", "..kdwkddk.......", "..kdddddkfff....", "..kdddddkfff....", "..kdddddk.......", ".kddddddddk.....", "kdddeeedddddk...", "kdddeeedddddk...", "kdddeeedddddk...", "kddddddddddk....", ".kddddddddk.....", "..kdddddk.......", "...f..f.f.......", "................"],
        "duckT": ["....................", "......KKKK..........", ".....KYYYYK.........", "....KYWKYYYK........", "....KYYYYYYKOOO.....", "....KYYYYYYKOOO.....", ".....KYYYYK.........", ".....KYYYYK.........", "....KYYYYYYKK.......", "...KYYYYYYYYYK......", "..KYYYxxxxYYYYK.....", "..KYYxxxxxxYYYK.....", "..KYYxxxxxxYYYK.....", "...KYYxxxxYYYYK.....", "....KYYYYYYYYK......", ".....KKKKKKKK.......", "......O...O........."],
        "duckling": ["................", "................", "......KKKK......", ".....KYYYYK.....", "....KYYYYYYK....", "....KYWBYYK.....", "....KYYYYYYK....", "...KYYYYYYYKOO..", "...KYYYYYYYKOO..", "...KYYYYYYYYK...", "...KYYYYYYYYK...", "...KYYYYYYYYK...", "....KYYYYYYK....", ".....KYYYYK.....", ".....O..O.......", "................"],
        "ducklingP": ["................", "................", "......kkkk......", ".....kddddk.....", "....kddddddk....", "....kdwkddk.....", "....kddddddk....", "...kddddddddkff.", "...kddddddddkff.", "...kddddddddk...", "...kddddddddk...", "...kddddddddk...", "....kddddddk....", ".....kddddk.....", ".....f..f.......", "................"],
        "egg": ["................", "......KKKK......", ".....KCCCCK.....", "....KCCCCCCK....", "...KCCCsCCCK....", "...KCsCCCCCK....", "..KCCCCCsCCCK...", "..KCCsCCCCCCK...", "..KCCCCCCsCCK...", "..KCsCCCCCCCK...", "..KCCCCsCCCCK...", "...KCCCCCCCK....", "...KCCCCCCCK....", "....KCCCCCK.....", ".....KKKKK......", "................"],
        "eggP": ["................", "......kkkk......", ".....kcccck.....", "....kcccccck....", "...kcccccccck...", "...kccclcccck...", "..kcccccccccck..", "..kcccclccccck..", "..kcccccccccck..", "..kccccccclcck..", "...kcccccccck...", "...kcccccccck...", "....kcccccck....", ".....kkkkkk.....", "................", "................"],
        "hatch": ["................", "......KKKK......", ".....KYYYYK.....", "....KYWBYYK.....", "....KYYYYYYK....", "...KCCCCCCCCK...", "..KCCsCCCCsCCK..", "..KCCCCCsCCCCK..", "..KCsCCCCCCsCK..", "..KCCCCsCCCCCK..", "...KCCCCCCCCK...", "...KCCCCCCCCK...", "....KCCCCCCK....", ".....KKKKKK.....", "................", "................"],
        "kitten": ["................", "................", "....K....K......", "....KgK.KgK.....", "...KggKKggK.....", "...KgggggggK....", "...KgWBgWBgK....", "...KgggpgggK....", "...KgggggggK....", "....KgggggK.K...", "....KgggggKKgK..", ".....KgggK.KK...", "......K.K.......", "................", "................", "................"],
        "noble": ["................", "....KKKK........", "...KYYYYK.......", "..KYWBYYK.......", "..KYYYYYKOOO....", "..KYYYYYKOOO....", "..KRRRRRK.......", ".KYYYYYYYYK.....", "KYYYyyyYYYYK....", "KYYYyyyYYYYK....", "KYYYyyyYYYYK....", "KYYYYYYYYYYK....", ".KYYYYYYYYK.....", "..KYYYYYYK......", "...O..O.O.......", "................"],
        "pixelA": ["....................", "....M.......M.......", ".....M.....M........", "....MMMMMMMMM.......", "...MM.MMMMM.MM......", "..MMMMMMMMMMMMM.....", "..M.MMMMMMMMM.M.....", "..M.M.......M.M.....", ".....MM...MM........", "....M..M.M..M......."],
        "pixelB": ["....................", "......M...M.........", ".......M.M..........", "......MMMMM.........", ".....MM.M.MM........", ".....MMMMMMM........", "......M...M.........", ".....M.....M........"],
        "pixelCrown": [".....Y.Y.Y......", ".....YYYYY......", "...M.......M....", "....M.....M.....", "...MMMMMMMMM....", "..MM.MMMMM.MM...", ".MMMMMMMMMMMMM..", ".M.MMMMMMMMM.M..", ".M.M.......M.M..", "....MM...MM.....", "................", "................", "................", "................", "................", "................"],
        "pixelHat": [".....KKKKK......", ".....KKKKK......", ".....KYYYK......", "....KKKKKKK.....", "...M.......M....", "....M.....M.....", "...MMMMMMMMM....", "..MM.MMMMM.MM...", ".MMMMMMMMMMMMM..", ".M.MMMMMMMMM.M..", ".M.M.......M.M..", "....MM...MM.....", "................", "................", "................", "................", "................", "................"],
        "pixelT": ["....................", ".....M.....M........", "......M...M.........", ".....MMMMMMM........", "....MM.MMM.MM.......", "...MMMMMMMMMMM......", "...M.MMMMMMM.M......", "...M.M.....M.M......", "......MM.MM........."],
        "plant": ["................", ".......t........", ".....tTtTt......", "....KtTTTtK.....", "...KtTWBTTtK....", "...KtTTTTTtK....", "....KtTTTtK.....", ".t...KTTK...t...", "tTt...KK...tTt..", ".t....KK....t...", "...KKKKKKKKK....", "...KOOOOOOOK....", "....KOOOOOK.....", "....KOOOOOK.....", ".....KKKKK......", "................"],
        "plantA": ["....................", ".......KKKK.........", ".....KKppppKK.......", "....KppppppppK......", "...KppKYYYYKppK.....", "...KppKYKKYKppK.....", "...KppKYYYYKppK.....", "....KppppppppK......", ".....KKKppKKK.......", "....t..KtK..t.......", "....KtKKtKKtK.......", ".....KtKtKtK........", "......KKtKK.........", ".......KtK..........", ".....KKKKKKK........", "....KOOOOOOOK.......", "....KOWKOKWOK.......", "....KOOOOOOOK.......", ".....KKKKKKK........"],
        "plantB": ["....................", "........KK..........", ".......KtTK.........", "......KtTTtK........", ".......KtK..........", ".......KtK..........", ".....KKKKKKK........", "....KOOOOOOOK.......", "....KOOOOOOOK.......", ".....KOOOOOK........", ".....KKKKKKK........"],
        "plantCrown": [".....Y.Y.Y......", ".....YYYYY......", ".......t........", ".....tTtTt......", "....KtTTTtK.....", "...KtTWBTTtK....", "...KtTTTTTtK....", "....KtTTTtK.....", ".t...KTTK...t...", "tTt...KK...tTt..", ".t....KK....t...", "...KKKKKKKKK....", "...KOOOOOOOK....", "....KOOOOOK.....", "....KOOOOOK.....", ".....KKKKK......", "................"],
        "plantHat": [".....KKKKK......", ".....KKKKK......", ".....KYYYK......", "....KKKKKKK.....", ".......t........", ".....tTtTt......", "....KtTTTtK.....", "...KtTWBTTtK....", "...KtTTTTTtK....", "....KtTTTtK.....", ".t...KTTK...t...", "tTt...KK...tTt..", ".t....KK....t...", "...KKKKKKKKK....", "...KOOOOOOOK....", "....KOOOOOK.....", "....KOOOOOK.....", ".....KKKKK......", "................"],
        "plantT": ["....................", ".......KKK..........", "......KpppK.........", "......KpppK.........", ".......KtK..........", "....Kt.KtK.tK.......", ".....KtKtKtK........", ".......KtK..........", ".....KKKKKKK........", "....KOOOOOOOK.......", "....KOWKOKWOK.......", "....KOOOOOOOK.......", ".....KKKKKKK........"],
        "pup": ["................", "................", "....KKKK........", "...KNNNNK.......", "..KnKWBNK.......", "..KnKNNNKK......", "...KNNNNKnK.....", "...KNNNNNK......", "..KNNNNNNNK.....", "..KNnnNNNNK.....", "...KNNNNNK......", "....K..K........", "................", "................", "................", "................"],
        "royal": ["..s.s.s.........", "..sssss.........", "....KKKK........", "...KYYYYK.......", "..KYWBYYK.......", "..KYYYYYKOOO....", "..KYYYYYKOOO....", "..KYYYYYK.......", ".KYYYYYYYYK.....", "KYYYyyyYYYYK....", "KYYYyyyYYYYK....", "KYYYYYYYYYYK....", ".KYYYYYYYYK.....", "..KYYYYYYK......", "...O..O.O.......", "................"],
        "royalP": [".o.o.o..........", ".ooooo..........", "...kkkk.........", "..kddddk........", ".kdwkddk........", ".kdddddkfff.....", ".kdddddkfff.....", ".kdddddk........", "kddddddddk......", "kdddeeedddddk...", "kdddeeedddddk...", "kddddddddddk....", ".kddddddddk.....", "..kdddddk.......", "...f..f.f.......", "................"],
        "sprout": ["................", "................", "................", "......t.t.......", ".....tTtTt......", "......KTK.......", "......KTK.......", "....KKKKKKK.....", "....KOWBOOK.....", ".....KOOOK......", ".....KKKKK......", "................", "................", "................", "................", "................"],
        "tot": ["................", "................", "................", "......KKKK......", ".....KtTTtK.....", "....KtTsTTtK....", "....KttttttK....", ".....KKKKKKKK...", "......Kt.KtWK...", "......KK.KKK....", "................", "................", "................", "................", "................", "................"],
        "turtle": ["................", "................", ".....KKKKK......", "....KtTTTtK.....", "...KtTsTTsTK....", "..KtTTsTTsTtK...", "..KtTTTTTTTtK...", "..KttttttttttK..", "...KKKKKKKKKKKK.", "....Kt..Kt..KtWK", "....KK..KK..KtK.", "............KK..", "................", "................", "................", "................"],
        "turtleA": ["....................", "......KKKKKK........", "....KKADDDDAKK......", "...KADDADADDDAK.....", "..KADDADDDDADDAK....", "..KADADDDDDDADAK....", ".KAADDDDDDDDDDAK....", ".KAAAAAAAAAAAAAK....", "KDDDDDDDDDDDDDDDKKK.", "KKKKKKKKKKKKKKKKtWtK", "..KttK....KttK.KtttK", "..KttK....KttK..KKK.", "..KKKK....KKKK......"],
        "turtleB": ["....................", ".......KKKK.........", ".....KKADDAKK.......", "....KADDDDDDAK......", "....KADADDADAK......", "...KAAAAAAAAAAK.....", "..KDDDDDDDDDDDKKK...", "..KKKKKKKKKKKKtWK...", "...KttK..KttK.KtK...", "...KKK...KKK..KK...."],
        "turtleCrown": [".......Y.Y.Y....", ".......YYYYY....", ".....KKKKK......", "....KtTTTtK.....", "...KtTsTTsTK....", "..KtTTsTTsTtK...", "..KtTTTTTTTtK...", "..KttttttttttK..", "...KKKKKKKKKKKK.", "....Kt..Kt..KtWK", "....KK..KK..KtK.", "............KK..", "................", "................", "................", "................"],
        "turtleHat": [".......KKKKK....", ".......KKKKK....", ".......KYYYK....", "......KKKKKKK...", ".....KKKKK......", "....KtTTTtK.....", "...KtTsTTsTK....", "..KtTTsTTsTtK...", "..KtTTTTTTTtK...", "..KttttttttttK..", "...KKKKKKKKKKKK.", "....Kt..Kt..KtWK", "....KK..KK..KtK.", "............KK..", "................", "................", "................", "................"],
        "turtleT": ["....................", "......KKKKK.........", "....KKADDDAKK.......", "...KADDADDDDAK......", "...KADDDDDADAK......", "..KADADDDDDDDAK.....", "..KAAAAAAAAAAAK.....", ".KDDDDDDDDDDDDDKKK..", ".KKKKKKKKKKKKKKtWtK.", "...KttK...KttK.KttK.", "...KKK....KKK...KK.."],
    ]
}
